import { PublicStation, AdminStation, AiRecommendation, EventLog, FeedbackSubmission } from '../types';

export const fallbackStations: PublicStation[] = [
  {
    stationId: "ST-KNY-01",
    name: "Kampüs Ana Giriş Akıllı Durak",
    description: "Selçuk Üniversitesi Alaeddin Keykubat Kampüsü ana girişinde konumlu, yüksek öğrenci ve ziyaretçi sirkülasyonuna sahip döngüsel enerji durağı.",
    coordinates: [38.0028, 32.5186],
    status: "aktif",
    lastUpdated: "2026-09-26T09:25:00Z",
    usbCPorts: 8,
    powerOutlets: 4,
    wirelessCharging: true,
    hvacStatus: "Aktif (Akıllı Isıtma / Soğutma)",
    accessibility: "Tam Uyumlu (Tekerlekli Sandalye Rampası, Braille & Sesli Bilgilendirme)",
    batteryReadiness: "yeterli",
    solarProductionKw: 5.4,
    instantConsumptionKw: 1.6,
    dailyCleanEnergyRatio: 96,
    gridFeedEnergyKwh: 22.8,
    indoorTemperature: 22.0,
    indoorHumidity: 41,
    airQuality: "Mükemmel (AQI 18 - PM2.5: 4 µg/m³)",
    maintenanceMessage: null,
    energyCabinet: {
      location: "Durağın arkasında, yolcu bekleme alanından ayrı bağımsız zemin kabini",
      isLocked: true,
      isVentilated: true,
      isFireResistant: true,
      safetySummary: "Batarya oturma alanında değil; ayrı güvenli enerji kabininde korunur."
    },
    isDemoData: true,
    policyNotice: "Halk API’sinde teknik telemetri paylaşımı tasarım gereği engellenmiştir; bu ayrım otomatik testlerle doğrulanmıştır."
  },
  {
    stationId: "ST-KNY-02",
    name: "Alaaddin Bulvarı Akıllı Durak",
    description: "Konya tarihi şehir merkezinde, Alaaddin Tepesi eteklerindeki yoğun aktarma noktasında hizmet veren güneş destekli durak.",
    coordinates: [37.8728, 32.4925],
    status: "aktif",
    lastUpdated: "2026-09-26T09:28:00Z",
    usbCPorts: 6,
    powerOutlets: 2,
    wirelessCharging: true,
    hvacStatus: "Aktif (Doğal Havalandırma + Eco Klima)",
    accessibility: "Tam Uyumlu (Tekerlekli Sandalye Alanı & Dokunsal Zemin)",
    batteryReadiness: "yeterli",
    solarProductionKw: 4.8,
    instantConsumptionKw: 2.1,
    dailyCleanEnergyRatio: 92,
    gridFeedEnergyKwh: 16.5,
    indoorTemperature: 23.2,
    indoorHumidity: 39,
    airQuality: "İyi (AQI 32 - PM2.5: 8 µg/m³)",
    maintenanceMessage: null,
    energyCabinet: {
      location: "Durağın sağ yanında, korumalı servis koridorunda ayrı kabin",
      isLocked: true,
      isVentilated: true,
      isFireResistant: true,
      safetySummary: "Batarya oturma alanında değil; ayrı güvenli enerji kabininde korunur."
    },
    isDemoData: true,
    policyNotice: "Halk API’sinde teknik telemetri paylaşımı tasarım gereği engellenmiştir; bu ayrım otomatik testlerle doğrulanmıştır."
  },
  {
    stationId: "ST-KNY-03",
    name: "Selçuklu Kongre Merkezi Akıllı Durak",
    description: "Selçuklu Kongre Merkezi ve Yeni İstanbul Caddesi aksındaki kültür-sanat etkinliği yolcularına yönelik akıllı durak.",
    coordinates: [37.9255, 32.4998],
    status: "sinirli",
    lastUpdated: "2026-09-26T09:20:00Z",
    usbCPorts: 4,
    powerOutlets: 1,
    wirelessCharging: false,
    hvacStatus: "Sınırlı Güç Modu (Eco Havalandırma)",
    accessibility: "Tam Uyumlu (Rampa ve Geniş Giriş)",
    batteryReadiness: "sinirli",
    solarProductionKw: 2.1,
    instantConsumptionKw: 1.9,
    dailyCleanEnergyRatio: 78,
    gridFeedEnergyKwh: 4.2,
    indoorTemperature: 24.5,
    indoorHumidity: 46,
    airQuality: "İyi (AQI 29)",
    maintenanceMessage: "Kısmi gölgelenme ve batarya koruma modu devrede. Şarj noktaları dönüşümlü hizmet vermektedir.",
    energyCabinet: {
      location: "Durağın arkasında, yolcu oturma bölmesinden bağımsız kilitli kabin",
      isLocked: true,
      isVentilated: true,
      isFireResistant: true,
      safetySummary: "Batarya oturma alanında değil; ayrı güvenli enerji kabininde korunur."
    },
    isDemoData: true,
    policyNotice: "Halk API’sinde teknik telemetri paylaşımı tasarım gereği engellenmiştir; bu ayrım otomatik testlerle doğrulanmıştır."
  },
  {
    stationId: "ST-KNY-04",
    name: "Karatay Bilim Merkezi Akıllı Durak",
    description: "TÜBİTAK destekli Konya Bilim Merkezi ve Şehir Parkı girişinde yer alan, yüksek kapasiteli temiz enerji durağı.",
    coordinates: [37.8885, 32.5590],
    status: "aktif",
    lastUpdated: "2026-09-26T09:30:00Z",
    usbCPorts: 8,
    powerOutlets: 4,
    wirelessCharging: true,
    hvacStatus: "Aktif (Tam Kapasite HVAC)",
    accessibility: "Tam Uyumlu (Engelli Aracı Hızlı Şarj Yuvası Mevcut)",
    batteryReadiness: "yeterli",
    solarProductionKw: 6.2,
    instantConsumptionKw: 2.4,
    dailyCleanEnergyRatio: 98,
    gridFeedEnergyKwh: 31.2,
    indoorTemperature: 21.5,
    indoorHumidity: 38,
    airQuality: "Mükemmel (AQI 15)",
    maintenanceMessage: null,
    energyCabinet: {
      location: "Durağın sol yanında, mimari olarak entegre yangına dayanıklı kabin",
      isLocked: true,
      isVentilated: true,
      isFireResistant: true,
      safetySummary: "Batarya oturma alanında değil; ayrı güvenli enerji kabininde korunur."
    },
    isDemoData: true,
    policyNotice: "Halk API’sinde teknik telemetri paylaşımı tasarım gereği engellenmiştir; bu ayrım otomatik testlerle doğrulanmıştır."
  },
  {
    stationId: "ST-KNY-05",
    name: "Meram Park Akıllı Durak",
    description: "Meram Bağları ve yeşil vadi rekreasyon alanında yer alan, doğayla uyumlu ahşap ve kompozit mimarili durak.",
    coordinates: [37.8522, 32.4410],
    status: "bakimda",
    lastUpdated: "2026-09-26T08:15:00Z",
    usbCPorts: 0,
    powerOutlets: 0,
    wirelessCharging: false,
    hvacStatus: "Bakım Nedeniyle Kapalı",
    accessibility: "Rampa Mevcut (İç Alan Geçici Kapalı)",
    batteryReadiness: "bakimda",
    solarProductionKw: 0.0,
    instantConsumptionKw: 0.2,
    dailyCleanEnergyRatio: 0,
    gridFeedEnergyKwh: 0.0,
    indoorTemperature: 20.0,
    indoorHumidity: 45,
    airQuality: "İyi (AQI 22)",
    maintenanceMessage: "Yıllık periyodik panel revizyonu ve batarya güvenlik testleri yürütülmektedir. En yakın hizmet veren durak: Alaaddin Bulvarı.",
    energyCabinet: {
      location: "Durağın arkasında, yolcu alanından tamamen izole edilmiş teknik kabin",
      isLocked: false,
      isVentilated: true,
      isFireResistant: true,
      safetySummary: "Batarya oturma alanında değil; ayrı güvenli enerji kabininde korunur."
    },
    isDemoData: true,
    policyNotice: "Halk API’sinde teknik telemetri paylaşımı tasarım gereği engellenmiştir; bu ayrım otomatik testlerle doğrulanmıştır."
  },
  {
    stationId: "ST-KNY-06",
    name: "Kılıçarslan Gençlik Merkezi Akıllı Durak",
    description: "Şehir Meydanı ve Kılıçarslan Gençlik Merkezi önündeki gençlik buluşma noktasında konumlanmış akıllı durak.",
    coordinates: [37.8785, 32.4845],
    status: "baglanti_yok",
    lastUpdated: "2026-09-26T07:40:00Z",
    usbCPorts: 4,
    powerOutlets: 2,
    wirelessCharging: true,
    hvacStatus: "Otonom Çalışıyor (Son Bilinen)",
    accessibility: "Tam Uyumlu (Sesli Rehber & Rampa)",
    batteryReadiness: "yeterli",
    solarProductionKw: 3.8,
    instantConsumptionKw: 1.5,
    dailyCleanEnergyRatio: 88,
    gridFeedEnergyKwh: 11.0,
    indoorTemperature: 22.8,
    indoorHumidity: 43,
    airQuality: "İyi (AQI 30)",
    maintenanceMessage: "Telemetri sunucu bağlantısı güncelleniyor. Durak içi fiziksel hizmetler yerel kontrol ünitesiyle çalışmaya devam etmektedir.",
    energyCabinet: {
      location: "Durağın arkasında, yolcu alanından bağımsız korunaklı kabin",
      isLocked: true,
      isVentilated: true,
      isFireResistant: true,
      safetySummary: "Batarya oturma alanında değil; ayrı güvenli enerji kabininde korunur."
    },
    isDemoData: true,
    policyNotice: "Halk API’sinde teknik telemetri paylaşımı tasarım gereği engellenmiştir; bu ayrım otomatik testlerle doğrulanmıştır."
  }
];

export const fallbackAiRecommendations: AiRecommendation[] = [
  {
    id: "AI-REC-01",
    stationId: "ST-KNY-04",
    stationName: "Karatay Bilim Merkezi",
    priority: "Yüksek",
    title: "Güneş Üretimi Yüksek: Batarya Şarjına Öncelik Ver",
    reason: "Anlık ışınım 880 W/m² seviyesinde ve üretim (6.2 kW) tüketimden (2.4 kW) yüksek. Akşam saatleri için bataryayı %100 seviyesine çıkarmak verimliliği maksimize eder.",
    expectedImpact: "+%14 pik saat enerji tasarrufu, sıfır şebeke çekişi.",
    timestamp: "2026-09-26T09:10:00Z",
    actionCommand: "PRIORITIZE_BATTERY_CHARGE",
    status: "pending"
  },
  {
    id: "AI-REC-02",
    stationId: "ST-KNY-02",
    stationName: "Alaaddin Bulvarı",
    priority: "Orta",
    title: "Akşam Yoğunluğu Öncesi Rezerv Oluştur",
    reason: "17:30 - 19:30 saatleri arasında yolcu şarj talebi %65 artmaktadır. Mevcut SOC (%79.5) seviyesinin korunması önerilir.",
    expectedImpact: "Kesintisiz 8 port USB-C ve kablosuz şarj sürekliliği.",
    timestamp: "2026-09-26T08:55:00Z",
    actionCommand: "RESERVE_CAPACITY_PEAK",
    status: "pending"
  },
  {
    id: "AI-REC-03",
    stationId: "ST-KNY-03",
    stationName: "Selçuklu Kongre Merkezi",
    priority: "Yüksek",
    title: "Batarya Sıcaklığı Yüksek: Güç Sınırla & Tasarruf Moduna Geç",
    reason: "Hücre sıcaklığı 27.5°C'ye ulaştı ve SOC %38.6. Batarya ömrünü korumak için kablosuz şarj sınırlandırılmalı ve fan devri artırılmalı.",
    expectedImpact: "Hücre sıcaklığında 2.5°C düşüş, termal stres önleme.",
    timestamp: "2026-09-26T09:05:00Z",
    actionCommand: "POWER_THROTTLE_COOLING",
    status: "pending"
  },
  {
    id: "AI-REC-04",
    stationId: "ST-KNY-01",
    stationName: "Kampüs Ana Giriş",
    priority: "Düşük",
    title: "Şebeke Aktarım Değerlendirmesi",
    reason: "Şebeke aktarımı; ilgili mevzuat, dağıtım şirketi bağlantısı ve teknik uygunluğa bağlı planlanan özelliktir. Fazla 22.8 kWh enerjinin şebeke senkron testi değerlendirilebilir.",
    expectedImpact: "Döngüsel mikro şebekeye temiz enerji katkısı.",
    timestamp: "2026-09-26T07:30:00Z",
    actionCommand: "SIMULATE_GRID_INJECTION",
    status: "pending"
  }
];
